Adding the read/write functions
AFulleringer/language-programmes-IFT6670A pull request #3
Opened 2023-04-27 18:06 UTC by AFulleringer

Added the read and write functions - need to be validated with actual prompts.

2023-04-28 19:06 UTC, gebelangsn approved these changes
LGTM! maybe wait for Kyle to merge his branch, then pull from master and push to this branch before merging... (just to make sure no conflicts)

2023-04-28 22:07 UTC, kylrth requested changes
I've got some suggestions! Isn't code review fun

2023-04-28 22:07 UTC, kylrth commented on src/affordance/tasks/tools.py
> +import pickle
Put this import up with the other imports so it can be sorted in

2023-04-28 22:07 UTC, kylrth commented on src/affordance/tasks/tools.py
> +        print('run dict not found, creating a new one!')
```suggestion
        print("creating a new dict for run:", run_title)
```

2023-04-28 22:07 UTC, kylrth commented on src/affordance/tasks/tools.py
> +    with open(f'{run_title}.pickle', 'wb') as handle:
We should make it possible to choose the directory for this with a flag. Or to save time we should just change it to somewhere not in cwd, maybe `./kvstore` or something?

2023-04-28 22:07 UTC, kylrth commented on src/affordance/tasks/tools.py
> +def read(key, run_title) -> tuple(str, str):
The way the code works currently, the first argument is the input text for the command, and the second argument is the output from the previous command. We should probably change the way the tools are called across the board, so they all have three arguments: a `run_title`, a `cmd_input`, and a `prev_output`. Mind adding that change into this PR?

2023-04-28 22:07 UTC, kylrth commented on src/affordance/tasks/tools.py
> +    return f"<key \'{key}\' did not exist>", None  # TODO: return a useful log message
These two returns are redundant, and whichever one you keep doesn't need to be in an else block

2023-04-28 22:07 UTC, kylrth commented on src/affordance/tasks/tools.py
> +
run the `black` formatter real quick

2023-04-28 22:07 UTC, kylrth commented on src/affordance/tasks/tools.py
> +    # text = God created the earth, light, and dark.
Maybe let's move some of these example comments into docstrings or something

2023-04-28 22:26 UTC, kylrth commented
Oh also don't forget to add this bit:

```python
    "[read]": read,
    "[write]": write,
    "[list keys]": list_keys,
```

In the tool dict

2023-04-28 23:08 UTC, AFulleringer commented
Somehow the changes to add run_title to visit and its lineage ended up in 'reduce cost of debug config' - just a heads up on where to look for that.

2023-04-29 01:21 UTC, kylrth commented on .vscode/launch.json
> +<<<<<<< HEAD
Haha somehow a merge conflict ended up here. It sounds like you have `commit`-ment issues!

I'm going to add one more commit to remove some of this stuff, and then when we're finished we can squash everything down into a single commit for posterity.

2023-04-29 01:21 UTC, kylrth commented on src/affordance/tasks/arxiv_summarization.py
> +import argparse
I actually think it's better to have a PR contain just one new thing at a time. Better to leave Georges' stuff in his branch

2023-04-29 01:21 UTC, kylrth commented on src/affordance/tasks/sequential_interpreter.py
> +    def batch_visit(
Sometimes this function is called with a batch across multiple separate evaluations, so we probably need to make `run_title` be a `List[str]`.

2023-04-29 01:21 UTC, kylrth commented on src/affordance/tasks/sequential_interpreter.py
> +        shifted_programs = individual_programs[: -(to_remove + 1)] + [
looks like I forgot to mention that I've been using `black --line-length 100`, which allows these lines to be longer. I'll fix that

2023-04-29 01:21 UTC, kylrth commented on src/affordance/tasks/sequential_interpreter.py
> +                    StacktraceItem(
We should log the run_title too

2023-04-29 01:31 UTC, kylrth commented
Alright once you make those few last changes, the last thing we need is to squash:

```sh
git fetch
git reset --soft origin/master
git commit -m "<a nice summary>"
git push -f
```

2023-04-30 19:21 UTC, kylrth approved these changes

2023-04-30 19:21 UTC, kylrth requested changes

2023-04-30 19:21 UTC, kylrth commented on .github/workflows/black.yml
> +    branches: [ main ]
You'll want to keep this

2023-04-30 19:38 UTC, kylrth approved these changes

2023-04-30 19:39 UTC, merged